export const productsData = [
    {
        id:1,
        title:'watch1',
        price:10,
        imageUrl:'./img/watch1.png',
    },
    {
        id:2,
        title:'watch2',
        price:10,
        imageUrl:'./img/watch2.png',
    },
    {
        id:3,
        title:'watch3',
        price:10,
        imageUrl:'./img/watch3.png',
    },
    {
        id:4,
        title:'watch4',
        price:10,
        imageUrl:'./img/watch4.png',
    },
    {
        id:5,
        title:'shirt1',
        price:10,
        imageUrl:'./img/shirt1.png',
    },
    {
        id:6,
        title:'shirt2',
        price:10,
        imageUrl:'./img/shirt2.png',
    },
    {
        id:7,
        title:'shirt3',
        price:10,
        imageUrl:'./img/shirt3.png',
    },
    {
        id:8,
        title:'shirt4',
        price:10,
        imageUrl:'./img/shirt4.png',
    },
    {
        id:9,
        title:'jewlery1',
        price:10,
        imageUrl:'./img/jewlery1.png',
    },
    {
        id:10,
        title:'jewlery2',
        price:10,
        imageUrl:'./img/jewlery2.png',
    },
    {
        id:11,
        title:'jewlery3',
        price:10,
        imageUrl:'./img/jewlery3.png',
    },
    {
        id:12,
        title:'jewlery4',
        price:10,
        imageUrl:'./img/jewlery4.png',
    },

];